url: https://122e4e-mapbox.global.ssl.fastly.net
api: https://122e4e-mapbox.global.ssl.fastly.net/core
tileApi: https://api-maps-staging.tilestream.net
permalink: /:categories/:title
baseurl: /mapbox-ios-sdk-legacy
version: v1.6.1
